In [76]:
import numpy as np
import pandas as pd
import openpyxl
from sklearn.model_selection import train_test_split

# Menampilkan data awal

In [45]:
df = pd.read_excel('StudentPerformanceFactors.xlsx')

df.head(20)

Hours_Studied  Attendance Parental_Involvement Access_to_Resources  \
0              23          84                  Low                High   
1              19          64                  Low              Medium   
2              24          98               Medium              Medium   
3              29          89                  Low              Medium   
4              19          92               Medium              Medium   
5              19          88               Medium              Medium   
6              29          84               Medium                 Low   
7              25          78                  Low                High   
8              17          94               Medium                High   
9              23          98               Medium              Medium   
10             17          80                  Low                High   
11             17          97               Medium                High   
12             21          83               Medium              Medium   
13              9          82               Medium              Medium   
14             10          78               Medium                High   
15             17          68               Medium              Medium   
16             14          60               Medium                 Low   
17             22          70                  Low              Medium   
18             15          80               Medium              Medium   
19             12          75               Medium                High   

   Extracurricular_Activities  Sleep_Hours  Previous_Scores Motivation_Level  \
0                          No            7               73              Low   
1                          No            8               59              Low   
2                         Yes            7               91           Medium   
3                         Yes            8               98           Medium   
4                         Yes            6               65           Medium   
5                         Yes            8               89           Medium   
6                         Yes            7               68              Low   
7                         Yes            6               50           Medium   
8                          No            6               80             High   
9                         Yes            8               71           Medium   
10                         No            8               88           Medium   
11                        Yes            6               87              Low   
12                        Yes            8               97              Low   
13                        Yes            8               72           Medium   
14                        Yes            8               74           Medium   
15                         No            8               70           Medium   
16                        Yes           10               65              Low   
17                        Yes            6               82           Medium   
18                        Yes            9               91              Low   
19                        Yes            7               58           Medium   

   Internet_Access  Tutoring_Sessions Family_Income Teacher_Quality  \
0              Yes                  0           Low          Medium   
1              Yes                  2        Medium          Medium   
2              Yes                  2        Medium          Medium   
3              Yes                  1        Medium          Medium   
4              Yes                  3        Medium            High   
5              Yes                  3        Medium          Medium   
6              Yes                  1           Low          Medium   
7              Yes                  1          High            High   
8              Yes                  0        Medium             Low   
9              Yes                  0          High       

# Mengecek tipe data  

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   Hours_Studied               6607 non-null   int64 
 1   Attendance                  6607 non-null   int64 
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64 
 6   Previous_Scores             6607 non-null   int64 
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64 
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   obje

# Mengecek Missing Value


In [47]:
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [49]:
nan_rows = df[df.isnull().T.any()]
nan_rows

Hours_Studied  Attendance Parental_Involvement Access_to_Resources  \
33               14          60                 High              Medium   
240              15          87                  Low              Medium   
275              23          82                  Low              Medium   
316              24          90                  Low                 Low   
359              15          64               Medium              Medium   
...             ...         ...                  ...                 ...   
6494             14          77               Medium              Medium   
6496             26          77                  Low              Medium   
6502             23          64               Medium              Medium   
6589             22          90                  Low                High   
6594              9          90                 High                High   

     Extracurricular_Activities  Sleep_Hours  Previous_Scores  \
33                           No            5               50   
240                          No            4               54   
275                         Yes            8               94   
316                          No            7               83   
359                         Yes            6               76   
...                         ...          ...              ...   
6494                        Yes            4               81   
6496                        Yes            7               71   
6502                         No            7               75   
6589                         No            5               99   
6594                        Yes            7               79   

     Motivation_Level Internet_Access  Tutoring_Sessions Family_Income  \
33             Medium             Yes                  2        Medium   
240            Medium             Yes                  1        Medium   
275            Medium             Yes                  1        Medium   
316            Medium             Yes                  0           Low   
359              High             Yes                  2        Medium   
...               ...             ...                ...           ...   
6494              Low             Yes                  3        Medium   
6496             High             Yes                  3          High   
6502           Medium             Yes                  2        Medium   
6589           Medium             Yes                  1           Low   
6594              Low             Yes                  4          High   

     Teacher_Quality School_Type Peer_Influence  Physical_Activity  \
33            Medium      Public        Neutral                  3   
240           Medium      Public        Neutral                  6   
275           Medium      Public       Negative                  2   
316           Medium     Private       Positive                  3   
359           Medium     Private       Positive                  4   
...              ...         ...            ...                ...   
6494          Medium     Private        Neutral                  3   
6496          Medium      Public        Neutral                  3   
6502            High      Public       Positive                  2   
6589             Low     Private       Positive                  2   
6594            High      Public       Positive                  4   

     Learning_Disabilities Parental_Education_Level Distance_from_Home  \
33                      No                  College                NaN   
240                     No                      NaN           Moderate   
275                    Yes              High School                NaN   
316                     No                  College                NaN   
359                    Yes              High School                NaN   
...                    ...                      ...                ...   
6494                    No                  College             

In [65]:
import pandas as pd

# Contoh DataFrame
data = {'Teacher_Quality': ['High', 'Low', 'Medium', None],
        'Parental_Education_Level': ['High School', 'College', 'PostGraduate', None],
        'Distance_from_Home': ['Near', 'Far', 'Moderate', None]}
df = pd.DataFrame(data)

# Cek nilai kosong sebelum diisi
print("Nilai kosong sebelum diisi:")
print(df.isnull().sum())

df['Teacher_Quality'] = df['Teacher_Quality'].fillna(df['Teacher_Quality'].mode()[0])
df['Parental_Education_Level'] = df['Parental_Education_Level'].fillna(df['Parental_Education_Level'].mode()[0])
df['Distance_from_Home'] = df['Distance_from_Home'].fillna(df['Distance_from_Home'].mode()[0])

# Cek nilai kosong setelah diisi
print("\nNilai kosong setelah diisi:")
print(df.isnull().sum())

# Tampilkan tabel yang sudah diisi nilai kosongnya
print("\nDataFrame setelah nilai kosong diisi:")
print(df)


Nilai kosong sebelum diisi:
Teacher_Quality             1
Parental_Education_Level    1
Distance_from_Home          1
dtype: int64

Nilai kosong setelah diisi:
Teacher_Quality             0
Parental_Education_Level    0
Distance_from_Home          0
dtype: int64

DataFrame setelah nilai kosong diisi:
  Teacher_Quality Parental_Education_Level Distance_from_Home
0            High              High School               Near
1             Low                  College                Far
2          Medium             PostGraduate           Moderate
3            High                  College                Far


In [66]:
df.isnull().sum()


Teacher_Quality             0
Parental_Education_Level    0
Distance_from_Home          0
dtype: int64

In [70]:
import pandas as pd

# Sample data
data = {'Teacher_Quality': ['High', 'Medium', 'Low', 'High', 'Medium']}

# Creating a DataFrame
df = pd.DataFrame(data)

# One-hot encoding for Teacher_Quality
df_one_hot = pd.get_dummies(df['Teacher_Quality'], dtype=int)

# Concatenating the original DataFrame with the one-hot encoded columns
df = pd.concat([df, df_one_hot], axis=1)

# Dropping the original Teacher_Quality column (optional)
df.drop('Teacher_Quality', axis=1, inplace=True)

# Display the result
print(df)


   High  Low  Medium
0     1    0       0
1     0    0       1
2     0    1       0
3     1    0       0
4     0    0       1


In [73]:
import pandas as pd

# Sample data
data = {
    'Teacher_Quality': ['High', 'Medium', 'Low', 'High', 'Medium'],
    'Hours_Studied': ['Few', 'Many', 'Average', 'Few', 'Many'],
    'Attendance': ['Good', 'Average', 'Poor', 'Good', 'Good'],
    'Sleep_Hours': ['Sufficient', 'Insufficient', 'Sufficient', 'Sufficient', 'Insufficient'],
    'Previous_Score': ['High', 'Medium', 'Low', 'High', 'Medium'],
    'Exam_Scores': ['Pass', 'Pass', 'Fail', 'Pass', 'Pass']
}

# Creating a DataFrame
df = pd.DataFrame(data)

# List of columns to one-hot encode
columns_to_encode = ['Teacher_Quality', 'Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Score', 'Exam_Scores']

# One-hot encoding the specified columns
df_encoded = pd.get_dummies(df, columns=columns_to_encode, dtype=int)

# Display the result
print(df_encoded)


   Teacher_Quality_High  Teacher_Quality_Low  Teacher_Quality_Medium  \
0                     1                    0                       0   
1                     0                    0                       1   
2                     0                    1                       0   
3                     1                    0                       0   
4                     0                    0                       1   

   Hours_Studied_Average  Hours_Studied_Few  Hours_Studied_Many  \
0                      0                  1                   0   
1                      0                  0                   1   
2                      1                  0                   0   
3                      0                  1                   0   
4                      0                  0                   1   

   Attendance_Average  Attendance_Good  Attendance_Poor  \
0                   0                1                0   
1                   1                0        

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Sample Data (replace this with your actual data)
data = {
    'Teacher_Quality': ['High', 'Medium', 'Low', 'High', 'Medium'],
    'Hours_Studied': ['Few', 'Many', 'Average', 'Few', 'Many'],
    'Attendance': ['Good', 'Average', 'Poor', 'Good', 'Good'],
    'Sleep_Hours': ['Sufficient', 'Insufficient', 'Sufficient', 'Sufficient', 'Insufficient'],
    'Previous_Score': ['High', 'Medium', 'Low', 'High', 'Medium'],
    'Exam_Scores': ['Pass', 'Pass', 'Fail', 'Pass', 'Pass']
}

# Create the DataFrame
df = pd.DataFrame(data)

# One-hot encode all categorical columns
df_encoded = pd.get_dummies(df, columns=df.columns, prefix=df.columns)

# Define the target column (assuming 'Exam_Scores_Pass' is the target)
X = df_encoded.drop('Exam_Scores_Pass', axis=1)  # Features
y = df_encoded['Exam_Scores_Pass']  # Target

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Optional: Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Display the training data
print("X_train_scaled:")
print(X_train_scaled)

print("\nX_test_scaled:")
print(X_test_scaled)


X_train_scaled:
[[-1.         -0.57735027  1.73205081 -0.57735027 -1.          1.73205081
   0.          0.57735027 -0.57735027  1.73205081 -1.73205081 -1.
  -0.57735027  1.73205081 -0.57735027]
 [-1.          1.73205081 -0.57735027  1.73205081 -1.         -0.57735027
   0.         -1.73205081  1.73205081 -0.57735027  0.57735027 -1.
   1.73205081 -0.57735027  1.73205081]
 [ 1.         -0.57735027 -0.57735027 -0.57735027  1.         -0.57735027
   0.          0.57735027 -0.57735027 -0.57735027  0.57735027  1.
  -0.57735027 -0.57735027 -0.57735027]
 [ 1.         -0.57735027 -0.57735027 -0.57735027  1.         -0.57735027
   0.          0.57735027 -0.57735027 -0.57735027  0.57735027  1.
  -0.57735027 -0.57735027 -0.57735027]]

X_test_scaled:
[[-1.         -0.57735027  1.73205081 -0.57735027 -1.          1.73205081
   1.         -1.73205081 -0.57735027  1.73205081 -1.73205081 -1.
  -0.57735027  1.73205081 -0.57735027]]


In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Sample data (replace with your actual data)
data = {
    'Hours_Studied': [2, 5, 8, 1, 4],
    'Attendance': [80, 85, 75, 90, 88],
    'Sleep_Hours': [6, 7, 5, 8, 6],
    'Previous_Score': [50, 60, 70, 55, 65],
    'Exam_Scores': [70, 85, 90, 60, 80]  # Target (continuous)
}

# Create the DataFrame
df = pd.DataFrame(data)

# Define features (X) and target (y)
X = df.drop('Exam_Scores', axis=1)  # Features
y = df['Exam_Scores']  # Target

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize scalers for X and y
scaler_X = StandardScaler()
scaler_y = StandardScaler()

# Fit the scaler on the training data and transform both X and y
X_train_scaled = scaler_X.fit_transform(X_train)
X_test_scaled = scaler_X.transform(X_test)

# Reshape y to fit the scaler (because it’s a 1D array)
y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1))
y_test_scaled = scaler_y.transform(y_test.values.reshape(-1, 1))

# Display the scaled data
print("X_train_scaled:\n", X_train_scaled)
print("\nX_test_scaled:\n", X_test_scaled)
print("\ny_train_scaled:\n", y_train_scaled)
print("\ny_test_scaled:\n", y_test_scaled)


X_train_scaled:
 [[ 0.09325048  0.78421393 -0.22941573  0.63245553]
 [ 1.58525817 -1.36205577 -1.14707867  1.26491106]
 [-0.65275337 -0.53656742 -0.22941573 -1.26491106]
 [-1.02575529  1.11440926  1.60591014 -0.63245553]]

X_test_scaled:
 [[0.4662524  0.28892092 0.6882472  0.        ]]

y_train_scaled:
 [[ 0.4472136 ]
 [ 1.34164079]
 [-0.4472136 ]
 [-1.34164079]]

y_test_scaled:
 [[0.89442719]]
